rules:
  # REGLAS DE SEGURIDAD PARA EL BACKEND
  
  - id: python-unsafe-json-loads
    pattern-either:
      - pattern: json.loads($DATA)
    message: "Deserialización JSON sin validación previa. Validar el contenido antes de procesar."
    languages: [python]
    severity: WARNING
    metadata:
      category: security
      cwe: "CWE-502: Deserialization of Untrusted Data"
      owasp: "A08:2021 - Software and Data Integrity Failures"
  
  - id: python-path-traversal
    pattern-either:
      - pattern: open($FILE, ...)
      - pattern: os.path.exists($FILE)
    message: "Posible Path Traversal. Validar y sanitizar rutas de archivos antes de usarlas."
    languages: [python]
    severity: WARNING
    metadata:
      category: security
      cwe: "CWE-22: Improper Limitation of a Pathname to a Restricted Directory"
      owasp: "A01:2021 - Broken Access Control"
  
  - id: python-websocket-no-origin-check
    pattern: |
      async def $FUNC(..., websocket: WebSocket, ...):
        ...
        await websocket.accept()
    message: "WebSocket acepta conexiones sin validar origen. Implementar verificación de origen."
    languages: [python]
    severity: ERROR
    metadata:
      category: security
      cwe: "CWE-346: Origin Validation Error"
      owasp: "A07:2021 - Identification and Authentication Failures"
  
  - id: python-websocket-input-validation
    pattern-either:
      - pattern: |
          $DATA = json.loads($RAW)
          ...
          $VAR = $DATA.get(...)
      - pattern: |
          $DATA.get($KEY)
    message: "Datos de WebSocket sin validación robusta. Implementar validación de esquema."
    languages: [python]
    severity: WARNING
    metadata:
      category: security
      cwe: "CWE-20: Improper Input Validation"
      owasp: "A03:2021 - Injection"

  # REGLAS DE SEGURIDAD PARA EL FRONTEND
  
  - id: typescript-innerhtml-xss
    pattern-either:
      - pattern: $EL.innerHTML = $VAR
      - pattern: $EL.innerHTML += $VAR
    message: "Uso de innerHTML puede causar XSS. Usar textContent o sanitizar con DOMPurify."
    languages: [typescript, javascript]
    severity: ERROR
    metadata:
      category: security
      cwe: "CWE-79: Cross-site Scripting (XSS)"
      owasp: "A03:2021 - Injection"
  
  - id: typescript-dangerous-eval
    pattern-either:
      - pattern: eval($CODE)
      - pattern: new Function($ARGS)
    message: "Uso de eval() o Function() permite ejecución de código arbitrario. Evitar."
    languages: [typescript, javascript]
    severity: ERROR
    metadata:
      category: security
      cwe: "CWE-95: Improper Neutralization of Directives in Dynamically Evaluated Code"
      owasp: "A03:2021 - Injection"
  
  - id: typescript-localstorage-no-validation
    pattern-either:
      - pattern: JSON.parse(localStorage.getItem($KEY))
      - pattern: JSON.parse($STORAGE.getItem(...))
    message: "Datos de localStorage parseados sin validación. Validar antes de usar."
    languages: [typescript, javascript]
    severity: WARNING
    metadata:
      category: security
      cwe: "CWE-502: Deserialization of Untrusted Data"
      owasp: "A08:2021 - Software and Data Integrity Failures"
  
  - id: typescript-websocket-error-handling
    pattern: |
      new WebSocket($URL)
    message: "WebSocket creado sin manejo robusto de errores. Implementar onerror y validación."
    languages: [typescript, javascript]
    severity: WARNING
    metadata:
      category: security
      cwe: "CWE-755: Improper Handling of Exceptional Conditions"
      owasp: "A04:2021 - Insecure Design"
